name: QwietAI Task


jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    
    container: shiftleft/core:latest
    
    steps:
    - uses: actions/checkout@v4

    
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    
    - name: NextGen Static Analysis
      run: |
        export QWIET_EXTERNAL_SECRETS=true
        export SHIFTLEFT_SBOM_GENERATOR=2
        
        ${GITHUB_WORKSPACE}/sl analyze --strict --wait --verbose --app secrets-java-demo-new  .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
